name: Selenium Login Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Debug - List directory contents
      run: |
        pwd
        ls -R
    
    - name: Run Selenium test
      env:
        USUARIO: ${{ secrets.CERTIFACT_USUARIO }}
        NIT: ${{ secrets.CERTIFACT_NIT }}
        CLAVE: ${{ secrets.CERTIFACT_CLAVE }}
      run: |
        python login_test.py
