name: Selenium Login Test
#Nombre del workflow

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
#Denificion de donde se ejecutara el workflow y en que branches

jobs:
  test:
    runs-on: ubuntu-latest
    #Define un trabajo llamado "test" que se ejecutará en la última versión de Ubuntu.

    steps:
    - uses: actions/checkout@v2
    #Verifica el repositorio en el runner

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    #Configura Python en el runner

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager
    #Instalacion de dependencias necesarias: selenium y webdriver-manager.

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    #Instala Google Chrome

    - name: Debug - List directory contents
      run: |
        pwd
        ls -R
    #Debugger para verificar que el script este en el repo

    - name: Debug - Show Selenium_script.py content
      run: |
        if [ -f Selenium_script.py ]; then
          echo "Content of Selenium_script.py:"
          cat Selenium_script.py
        else
          echo "Selenium_script.py not found!"
        fi
    #Muestra el contenido del script 

    - name: Run Selenium test
      env:
        USUARIO: ${{ secrets.CERTIFACT_USUARIO }}
        NIT: ${{ secrets.CERTIFACT_NIT }}
        CLAVE: ${{ secrets.CERTIFACT_CLAVE }}
      run: |
        python Selenium_script.py
    #Ejecuta el script de prueba de Selenium.
